### ISSUE TITLE
Download function does not work anymore

### ISSUE THREAD

**Issue by mfuhrmann** [owex/tabbypro#10]
There are multiple buttons to download the tabs as text file

![image](https://github.com/owex/tabbypro/assets/4995222/cc597879-5758-457b-a643-d91a443e2935)
![image](https://github.com/owex/tabbypro/assets/4995222/8f19927f-1ded-412d-bde4-5720751a1513)

But none if them work properly. No download starts.

**Comment by owex** [comment]
@mfuhrmann Oops my bad, this should be resolved now 😵‍💫
