### ISSUE TITLE
Arrows are working but place marker isn't moving. 

### ISSUE THREAD

**Issue by Murphdog1421** [owex/tabbypro#13]
Not able to correctly edit tabs due to when clicking the arrows to go back the place marker isn't moving with it and its a guessing game where it will land. 
Suggestion would be to be able to point and click on a number and be able to edit that number instead of having to scroll through the entire tab to get to one mistake.

**Comment by owex** [comment]
Thanks for flagging this, i'll get this fixed asap!

**Comment by owex** [comment]
@Murphdog1421 A hotfix is now deployed, i'll look to include a double click mechanism which will allow you to change the contents of the selected for now tho the arrows should work again and you can click to move the place marker i appreciate that at times it can be finicky as it doesn't replace whats selected when you add a new note,

**Comment by Murphdog1421** [comment]
I appreciate it. This site has helped me a lot with writing out tabs for worship team music. It's much cleaner.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
