### ISSUE TITLE
saving to account removed tab and fret board view. 

### ISSUE THREAD

**Issue by Murphdog1421** [owex/tabbypro#14]
when site opens i can click in the tab, add the name and everything works. as soon as i try to switch it to save on account everything disappears. the tab, the fretboard, all of it. I click on my tabs, which doesn't always work and when i click to edit it nothing appears.

**Comment by owex** [comment]
Thanks for flagging this now investigating! Sorry for the hassle!

**Comment by owex** [comment]
@Murphdog1421 I've finally been able to resolve this. The issue ultimately came about due to the hosting platform updating its engine so i've had to fix a few pieces of software at specific versions to restore order :)

**Comment by Murphdog1421** [comment]
Awesome. No worries.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
