### ISSUE TITLE
Using the delete on keyboard

### ISSUE THREAD

**Issue by Murphdog1421** [owex/tabbypro#18]
Just a suggestion. 
Being able to use the delete key on the keyboard to backspace instead of using the red x button. Being able to use the space bar to make a space is great. Being able to use the delete key would be helpful as well.

**Comment by owex** [comment]
Good ideal i'll look into this!

**Comment by owex** [comment]
@Murphdog1421 A release has just been deployed with this request completed, delete should now remove the last tab in the selected block.
