### ISSUE TITLE
Saving tabs sometimes deletes data

### ISSUE THREAD

**Issue by z0t0b** [owex/tabbypro#2]
On a few occasions I've saved a tab and refreshed to find none of the data saved for it. Not sure why this is happening but it made me lose some work :(

**Comment by owex** [comment]
Mmmm odd. Do you have any more info on the context of this failure e.g. browser, OS, incognito?

**Comment by z0t0b** [comment]
Hey sorry for the delayed response, it's on Chrome but I've seen it happen on Firefox too. I'm having a hard time reproducing it reliably, it seems to be at random

**Comment by z0t0b** [comment]
I'm on Windows 11 too
