### ISSUE TITLE
Not able to use repeat

### ISSUE THREAD

**Issue by jada2202** [owex/tabbypro#3]
![Screenshot 2023-11-06 213248](https://github.com/owex/tabbypro/assets/150100489/623cec6e-c91c-4aa4-bdeb-0d8a76be06c3)

I am not able to use repeat. It seems as though it is broken as it is hidden. When I type in a number, nothing happens. Please fix, and please get back to me as soon as it's fixed. I would appreciate it much, thank you!

**Comment by owex** [comment]
Thanks for reporting this, I’ve increased the size of repeat box and applied a fix to ensure the repeat is included in the downloaded tab txt file. 

Please let me know if everything is now working as you’d expect.

**Comment by jada2202** [comment]
![Screenshot 2023-11-07 102825](https://github.com/owex/tabbypro/assets/150100489/a50c2796-ca6f-4b21-acea-6105758250fc)
Hey I replied something else on twitter with the repeat that I am unable to do but it may be a user error. Thank you for your help! I'll be considering becoming a supporter for tabby pro!

**Comment by owex** [comment]
> ![Screenshot 2023-11-07 102825](https://user-images.githubusercontent.com/150100489/281092674-a50c2796-ca6f-4b21-acea-6105758250fc.png) Hey I replied something else on twitter with the repeat that I am unable to do but it may be a user error. Thank you for your help! I'll be considering becoming a supporter for tabby pro!

So currently repeats can only be defined at a block level, i think having the ability to set a repeat manually like the attached image is a good idea and i'll look to implement a solution for this and put this high on my TODOs.
<img width="301" alt="Screenshot 2023-11-07 at 17 15 56" src="https://github.com/owex/tabbypro/assets/1687789/5dc71225-d892-445d-a15d-dd7dd7190804">

**Comment by owex** [comment]
Updatd UI with new repeat option, it only goes up to x10, can extend if needed. Looking at the [UG guide](https://www.ultimate-guitar.com/contribution/help/rubric) they don't suggest adding repeats inside the stave block but its your tab so why not!

Also tidied up the techniques
<img width="1030" alt="Screenshot 2023-11-08 at 19 34 43" src="https://github.com/owex/tabbypro/assets/1687789/eb0bf2a3-45b8-4553-9006-df73a764d7f8">

**Comment by jada2202** [comment]
Thank you thank you thank you!!!!!!
