### ISSUE TITLE
Unable to edit saved tabs

### ISSUE THREAD

**Issue by jada2202** [owex/tabbypro#4]
When I try to edit or view my saved tabs, this error comes up...

![Screenshot 2023-11-28 203657](https://github.com/owex/tabbypro/assets/150100489/566f58c7-483b-4130-aabe-bf7fcf501f8d)

**Comment by owex** [comment]
Thanks for flagging this and i'm really sorry you've encountered this error i'll look into this as an urgent priority. I believe i've been able to replicate the issue, if you refresh the page does the tab load?

**Comment by jada2202** [comment]
No the error still comes up

**Comment by owex** [comment]
@jada2202 A fix has been applied and i've been able to successfully view/edit my tabs, are you still experiencing the issue now? Please logout of your account (top far right menu) and back in again and try again if it persists and let me know.
