### ISSUE TITLE
Add technique symbols for down/up strokes

### ISSUE THREAD

**Issue by mfuhrmann** [owex/tabbypro#6]
Here the first two notes get picked with two fingers the other one is a down stroke over all defined strings.
Would be handy to be able to define this.

![image](https://github.com/owex/tabbypro/assets/4995222/3b3509f5-189c-4b65-9a31-5cb1c8756ba8)

**Comment by owex** [comment]
Thanks for the suggestion, this has been on the horizon for some time and I’ve already laid some foundation for this so to speed things along do you think you could give me a few examples of various of techniques, up/down, slap/pop? And how you’d expect to see them in the output. 

thanks!

**Comment by mfuhrmann** [comment]
I think important techniques are covered. But I am also not super experienced on that.
Also, I would go little steps. If someone needs another technique that is missing, then let add it afterwards.

This page explains how to present them in normal and ASCII:
https://theacousticguitarist.com/how-to-read-guitar-tab/#How_to_read_guitar_tab_symbols

Regarding the up/down strokes I think a `D` or `U` below the line would make sense here. 
Because then there is still the chance to add the chord names above https://github.com/owex/tabbypro/issues/7
Important is, that we can see it in the text output and also in the web browser view.

Maybe like this?
```
e|-0-0-|-----0-|--------| 
B|---1-|-----1-|1---3---| 
G|---2-|---2-2-|0-0---0-| x1
D|---2-|-3---3-|--------| 
A|-0---|-------|3-------| 
E|-----|-------|--------| 
     D
```

**Comment by owex** [comment]
@mfuhrmann I've add a feature to allow you to set the strum technique for each column, a little plus symbol now appears below each column which opens a modal to do this. Let me know what you think.

<img width="158" alt="Screenshot 2024-02-24 at 21 59 54" src="https://github.com/owex/tabbypro/assets/1687789/a49712b4-12e7-4fa1-bfa1-65b21184c733">

**Comment by mfuhrmann** [comment]
This could work. I could also give it a try if you want. I didn't check it yet, is there a way to run this new branch?


Am 24. Februar 2024 23:01:57 MEZ schrieb Owen Rhodes ***@***.***>:

**Comment by mfuhrmann** [comment]
Ah! It is online already. Nice.
Seems to work as it should.

But it looks like the `D` is a bit cut off at the bottom:
![image](https://github.com/owex/tabbypro/assets/4995222/084a7040-840f-4b0a-9cef-4e78b3bc9a07)
I've tested with Chromium and Firefox. Same issue.

**Comment by owex** [comment]
@mfuhrmann  Ah thanks, the output should be unaffected by this bug so should be an easy fix.
