### ISSUE TITLE
There are left overs that can't be removed manually

### ISSUE THREAD

**Issue by mfuhrmann** [owex/tabbypro#8]
Once you've used some techniques in your tabs, and you remove them again, the don't disappear in this "view" view and also in the text output.

![image](https://github.com/owex/tabbypro/assets/4995222/da798997-16ca-4d12-bc3b-3aece723e3d1)

And it looks like there is no way of deleting it manually.

**Comment by owex** [comment]
@mfuhrmann You should be able to remove techniques now and the remove button should auto remove. Thanks for flagging this!
