### ISSUE TITLE
"View" view does not view the tabs

### ISSUE THREAD

**Issue by mfuhrmann** [owex/tabbypro#9]
![image](https://github.com/owex/tabbypro/assets/4995222/38c8b394-6a96-4e71-8060-cce416648927)
The "view" view does not show the tabs.

**Comment by owex** [comment]
@mfuhrmann My most recently fix should resolve this, if it doesn't do you think you could export this tab (from the My Tabs listing) and post the export file for testing. Thanks again for flagging
